[35mDEBUG   [0m test_Api:test_queryGeeAuthCode.py:13 this is warning message!!!
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:937 Starting new HTTPS connection (1): m.qccr.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 https://m.qccr.com:443 "GET /api/userprod/user/queryGeeAuthCode?t=1588304436890&api=superapi&phone=17046689470&type=1 HTTP/1.1" 200 45